MODEL:
  SKELETON_AUG:
    PRETRAIN_GBA: ""
  PRETRAIN_DIR: ""
  PRETRAIN_ITER: 0
SOLVER:
  BASE_LR: 0.001
  MAX_ITER: 30000 
  DECAY_ITER: 10000 
  LAMBDA_G_G: 1.  
  LAMBDA_S: 0.   
  LAMBDA_T: 1.  
  LAMBDA_A: 10.  
  LAMBDA_Z: 1.0  
  LAMBDA_I: 1.0 
DATALOADER:
  NUM_WORKERS: 8
TEST:
  PRETRAIN_G_Glyphy: ""